[project]
name = 'eco-stamps'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.eco-stamps]
path = 'contracts/eco-stamps.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
